### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sahlaysta** [Mahdi-Massahi/JavaFX-DarkTheme#1]
May I ask how you managed to change the color of the title bar? Mine stays white

**Comment by Mahdi-Massahi** [comment]
Hi @sahlaysta, thanks for asking;

> This is pretty much an OS dependent thing. The operating system gets to decide how titlebars and borders are displayed by default. However, it definitely can be done, if you are willing to venture into making your own title bar.
> 
> To start out, you will need to modify the application window's stage to StageStyle.UNDECORATED. Then you will need to set up your own borders and title bar (complete with things like the title, minimize button, close button, etc.). You can then add the border pane as a scene into your application's stage, and that should render your custom titlebar then without the default Windows styling.  

source: 
https://stackoverflow.com/questions/42583779/how-to-change-the-color-of-title-bar-in-framework-javafx
